name: Build APK (Release)

on:
    workflow_dispatch:

jobs:
  build-release:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Generate random keystore
      run: |
        keytool -genkeypair -alias random-key \
          -keyalg RSA -keysize 2048 -validity 365 \
          -keystore random.keystore \
          -storepass password \
          -keypass password \
          -dname "CN=Anonymous, OU=Dev, O=Anonymous, L=City, S=State, C=US"

    - name: Sign APK
      run: |
        jarsigner -verbose -keystore random.keystore \
          -storepass password \
          -keypass password \
          app/build/outputs/apk/release/*.apk random-key

    - name: Align APK
      run: |
        zipalign -v -p 4 app/build/outputs/apk/release/*.apk app/build/outputs/apk/release/aligned-release.apk

    - name: Verify APK signature
      run: jarsigner -verify app/build/outputs/apk/release/aligned-release.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: signed-aligned-release-apk
        path: app/build/outputs/apk/release/aligned-release.apk